---
- name: Create Virtual Service
  hosts: localhost
  connection: local
  collections:
    - vmware.alb
  vars_files:
    - creds.yml
    - vars.yml
  tasks:
    - name: Create VsVip
      vmware.alb.avi_vsvip:
        name: "{{ app_name }}-VsVip"
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        vrf_context_ref: "/api/vrfcontext/?name={{ vrf_name }}"
        tenant: "{{ tenant_name }}"
        cloud_ref: "/api/cloud/?name={{ cloud_name }}"
#       tier1_lr: "/infra/tier-1s/{{ t1_id }}"
        vip:
          - vip_id: '1'
            auto_allocate_floating_ip: false
            auto_allocate_ip: true
            avi_allocated_fip: false
            avi_allocated_vip: false
            prefix_length: 32
            auto_allocate_ip_type: V4_ONLY
            enabled: true
            ipam_network_subnet:
              network_ref: "/api/network/?name={{ ipam_network_name }}"
    - name: Create a Pool with health monitor
      vmware.alb.avi_pool:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        tenant: "{{ tenant_name }}"
        cloud_ref: "/api/cloud/?name={{ cloud_name }}"
        name: "{{ app_name }}-Pool"
        state: present
#       tier1_lr: "/infra/tier-1s/{{ t1_id }}"
        default_server_port: 80
        health_monitor_refs:
          - '/api/healthmonitor?name=System-HTTP'
        servers:
          - ip:
              addr: 100.64.21.21
              type: V4
          - ip:
              addr: 100.64.21.22
              type: V4
    - name: Create SSL Virtual Service
      vmware.alb.avi_virtualservice:
        avi_credentials: "{{ avi_credentials }}"
        name: "{{ app_name }}"
        state: present
        vsvip_ref: "/api/vsvip/?name={{ app_name }}-VsVip"
        services:
          - port: 80
          - port: 443
            enable_ssl: true
        ssl_profile_ref: "/api/sslprofile?name=System-Standard"
        application_profile_ref: "/api/applicationprofile?name=System-Secure-HTTP"
        waf_policy_ref: "/api/wafpolicy?name=System-WAF-Policy"
        ssl_key_and_certificate_refs:
          - '/api/sslkeyandcertificate?name=System-Default-Cert'
          - '/api/sslkeyandcertificate?name=System-Default-Cert-EC'
        tenant: "{{ tenant_name }}"
        cloud_ref: "/api/cloud/?name={{ cloud_name }}"
        pool_ref: "/api/pool?name={{ app_name }}-Pool"
